- name: Install pip python package
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - python-dev
    - python-pip
  register: kernel_result

- name: Install ansible
  pip: name=ansible

- name: Copy ansible template files
  copy:
    src: ansible
    dest: "/home/{{ remote.user }}/test-env/ansible"
    directory_mode: 0755
    owner: '{{ remote.user }}'
    group: '{{ remote.group }}'